charts/configmap: add S3GW_SERVICE_ADDRESS
aquarist-labs/s3gw-charts pull request #113
Opened 2023-07-30 11:15 UTC by jecluis

Adds a new configmap entry, pointing to the address of the s3gw service.

This will be consumed by the `s3gw-ui` backend.

We are leaving the original entry in there nonetheless so we don't break the UI if/when this gets merged, depending on whether changed to the UI get merged before or after. It should be removed in a coming release.

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

2023-07-31 07:28 UTC, m-ildefons approved these changes
There are no technical reasons not to approve, but:
- why the inconsistency `ADDRESS`/`URL` (also it's not an address, its a URL, right?)?
- why not just use `RGW_SERVICE_URL` since it's already there?

2023-09-13 13:04 UTC, jecluis commented
> There are no technical reasons not to approve, but:
> 
>     * why the inconsistency `ADDRESS`/`URL` (also it's not an address, its a URL, right?)?

sure, could be `_URL` instead, that's easily fixable.

>     * why not just use `RGW_SERVICE_URL` since it's already there?

because this is `s3gw`, and I kind of want to minimize external exposure to `rgw` concepts.

2023-09-13 13:13 UTC, giubacc requested changes

2023-09-13 13:13 UTC, giubacc commented on charts/s3gw/templates/configmap.yaml
> +  S3GW_SERVICE_ADDRESS: 'https://{{ include "s3gw.serviceName" . }}.{{ .Values.publicDomain }}'
shouldn't this be `S3GW_SERVICE_URL` ?

2023-09-13 15:15 UTC, jecluis commented
@m-ildefons @giubacc updated the PR to 1) make the variable `_URL`, and 2) to drop the unused `RGW_` counterpart.

2023-09-13 15:39 UTC, giubacc approved these changes

2023-09-13 15:49 UTC, jecluis commented
to be merged after aquarist-labs/s3gw-ui#242

2023-09-20 16:10 UTC, merged