Adding Rancher instructions to README.md
aquarist-labs/s3gw-charts pull request #34
Opened 2022-09-01 16:13 UTC by abonillabeeche

Added instructions to Install S3GW via Rancher

Signed-off-by: Alejandro Bonilla abonilla@suse.com

2022-09-02 07:58 UTC, giubacc commented
Thanks @abonillabeeche for contributing!
I think adding documentation specific for Rancher is a great idea.
I don't think btw, that this is the best place to add this kind of documentation; I'm more of the opinion to add a specific section/file about Rancher under our documentation at https://github.com/aquarist-labs/s3gw/tree/main/docs.
What do you think @jhmarina @jecluis ?
We also encourage opening an issue here https://github.com/aquarist-labs/s3gw for tracking purpose.

2022-09-02 14:57 UTC, jhmarina commented
> ... What do you think @jhmarina @jecluis ? We also encourage opening an issue here https://github.com/aquarist-labs/s3gw for tracking purpose.

-- 

Yes, the documentation should be added here: https://github.com/aquarist-labs/s3gw/tree/main/docs

The files in that folder are then used to generate this page: https://s3gw-docs.readthedocs.io/en/latest/

There's an issue created for moving this [documentation to the main `docs ` folder](https://github.com/aquarist-labs/s3gw/issues/81) we can use the issue to add these instructions too.

I'll close this PR and add it to the issue.

2022-09-02 15:49 UTC, abonillabeeche commented
When the chart is added into Rancher, it reads the README and shows the chart specific instructions, which allows the user to follow/have instructions at hand as they initially try and deploy the chart. If I add it where I did, the user will see it as they are in the process of installing via Rancher.

2022-09-05 07:45 UTC, giubacc commented
Personally, I would agree to have a minimum of documentation at hand.
But the team, at a certain point, decided to aggregate all the documentation and centralize it elsewhere.
We can discuss if a mixed approach could be better; but for the time being, we have that rule.

2022-09-05 07:59 UTC, jhmarina commented
I don’t have any issue with having minimal documentation available in the readme file. 

What we agreed on is having basic “Getting started” information on it and then all the remaining information in the documentation. 

Perhaps the info added in the PR should stay here

2022-09-05 08:44 UTC, jecluis commented
I think it makes sense to have some information on each repository, because otherwise potential users can be confused. Having even minimal information, or information that is relevant to have, and then having a link to the full documentation seems the way to go IMO.

So I don't see a problem with merging this PR.

2022-09-05 08:46 UTC, jhmarina commented
I reopened the PR. @abonillabeeche you’ll need to sign it off though. DCO is complaining

2022-09-05 08:58 UTC, giubacc requested changes

2022-09-05 08:58 UTC, giubacc commented on charts/s3gw/README.md
> +    -> Apps -> Repositories -> Create S3GW using the s3gw-charts Git URL https://github.com/aquarist-labs/s3gw-charts and the main branch
for consistency, I would rather write S3GW lowercase: 

```suggestion
    -> Apps -> Repositories -> Create s3gw using the s3gw-charts Git URL https://github.com/aquarist-labs/s3gw-charts and the main branch
```

2022-09-05 08:58 UTC, giubacc commented on charts/s3gw/README.md
> +    -> Apps -> Charts -> Install S3GW -> Storage -> Storage Type: pvc -> PVC Name: s3gw-pvc
for consistency, I would rather write S3GW lowercase:

```suggestion
    -> Apps -> Charts -> Install s3gw -> Storage -> Storage Type: pvc -> PVC Name: s3gw-pvc
```

2022-09-06 14:03 UTC, giubacc commented
@abonillabeeche would you mind to rebase your last commit and force push it with your commit?
We should avoid for the future proposing commits via github because they cannot be signed.

2022-09-13 12:17 UTC, jhmarina commented
After having a chat with @abonillabeeche we agreed that I'll include the changes introduced in this PR on a different issue:   * On the charts repo, add the information added by @abonillabeeche [here](https://github.com/aquarist-labs/s3gw-charts/pull/34)

2022-09-13 12:17 UTC, closed without merging